apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: ingress-auth-policy
spec:
  targets:
  - name: productpage
  origins:
  - jwt:
      issuer: "https://${keycloak_route}/auth/realms/istio/protocol/istio"
      jwksUri: "https://${keycloak_route}/auth/realms/istio/protocol/istio/protocol/openid-connect/certs"
  principalBinding: USE_ORIGIN